sudo: required
services:
    - docker

before_install:
    - docker build -t jilsx/react-test -f ./client/Dockerfile.dev ./client
    
script:
    #- docker run -e CI=true arnizzle/complex-fib npm run test
    - docker run -e CI=true jilsx/react-test npm test

after_success:
    - docker build -t jilsx/multi-client ./client
    - docker build -t jilsx/multi-server ./server
    - docker build -t jilsx/multi-nginx ./nginx
    - docker build -t jilsx/multi-worker ./worker
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push jilsx/multi-client
    - docker push jilsx/multi-server
    - docker push jilsx/multi-worker
    - docker push jilsx/multi-nginx

deploy:
    edge: true
    provider: elasticbeanstalk
    region: "eu-west-2"
    app: "complex-fib"
    env: "ComplexFib-env"
    bucket_name: elasticbeanstalk-eu-west-2-844569641877
    bucket_path: "docker-multi"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
